modLoader="javafml"
loaderVersion = "[47,)"
license="${mod_license}"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''